# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champ_chooser', '0002_auto_20170613_0654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summoner_v3',
            old_name='profile_icon_id',
            new_name='profileIconId',
        ),
        migrations.RenameField(
            model_name='summoner_v3',
            old_name='revision_date',
            new_name='revisionDate',
        ),
        migrations.RenameField(
            model_name='summoner_v3',
            old_name='summoner_id',
            new_name='summonerLevel',
        ),
        migrations.RemoveField(
            model_name='summoner_v3',
            name='summoner_level',
        ),
        migrations.AlterField(
            model_name='summoner_v3',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
