# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champ_chooser', '0005_auto_20170620_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummonerSpells',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('summonerLevel', models.IntegerField(default=None)),
                ('name', models.CharField(default=None, max_length=50)),
                ('key', models.CharField(default=None, max_length=60)),
                ('description', models.CharField(default=None, max_length=500)),
            ],
        ),
    ]
