# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 05:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('.league.champ_chooser', '0003_auto_20170613_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner_v3',
            name='region',
            field=models.CharField(default='NA1', max_length=5),
        ),
        migrations.AlterField(
            model_name='summoner_v3',
            name='revisionDate',
            field=models.IntegerField(default=datetime.datetime.now),
        ),
    ]
