# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('.league.champ_chooser', '0004_auto_20170620_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner_v3',
            name='revisionDate',
            field=models.IntegerField(default=0),
        ),
    ]
