# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 00:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league.champ_chooser', '0006_summonerspells'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SummonerSpells',
            new_name='SummonerSpell',
        ),
    ]
